# Generated by Django 5.0.2 on 2024-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
