# Generated by Django 5.0.2 on 2024-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoReal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('liga', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=50)),
                ('fecha', models.CharField(blank=True, max_length=50)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField(default=-1)),
                ('goles_visitante', models.IntegerField(default=-1)),
                ('puntos_local', models.IntegerField(default=-1)),
                ('puntos_visitante', models.IntegerField(default=-1)),
                ('winner', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PartidosEntrenamiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('liga', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
                ('puntos_local', models.IntegerField()),
                ('puntos_visitante', models.IntegerField()),
                ('goles_ultimos_5_partidos_equipo_local', models.IntegerField(default=-1)),
                ('goles_ultimos_5_partidos_equipo_visitante', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_equipo_local', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_equipo_visitante', models.IntegerField(default=-1)),
                ('goles_ultimos_5_partidos_local_siendo_local', models.IntegerField(default=-1)),
                ('goles_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_local_siendo_local', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_equipo_local', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_equipo_visitante', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_local_siendo_local', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField(default=-1)),
                ('falta', models.BooleanField(default=False)),
                ('winner', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PartidoSinPredecir',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('liga', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=50)),
                ('fecha', models.CharField(blank=True, max_length=50)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_ultimos_5_partidos_equipo_local', models.IntegerField(default=-1)),
                ('goles_ultimos_5_partidos_equipo_visitante', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_equipo_local', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_equipo_visitante', models.IntegerField(default=-1)),
                ('goles_ultimos_5_partidos_local_siendo_local', models.IntegerField(default=-1)),
                ('goles_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_local_siendo_local', models.IntegerField(default=-1)),
                ('puntos_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_equipo_local', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_equipo_visitante', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_local_siendo_local', models.IntegerField(default=-1)),
                ('goles_en_contra_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField(default=-1)),
                ('falta', models.BooleanField(default=False)),
            ],
        ),
    ]
