# Generated by Django 5.0.2 on 2024-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidosEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=50)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
                ('puntos_local', models.IntegerField()),
                ('puntos_visitante', models.IntegerField()),
                ('goles_ultimos_5_partidos_local', models.IntegerField()),
                ('goles_ultimos_5_partidos_visitante', models.IntegerField()),
                ('puntos_ultimos_5_partidos_local', models.IntegerField()),
                ('puntos_ultimos_5_partidos_visitante', models.IntegerField()),
                ('goles_ultimos_5_partidos_local_siendo_local', models.IntegerField()),
                ('goles_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField()),
                ('puntos_ultimos_5_partidos_local_siendo_local', models.IntegerField()),
                ('puntos_ultimos_5_partidos_visitante_siendo_visitante', models.IntegerField()),
                ('winner', models.CharField(max_length=1)),
            ],
        ),
    ]
