# Generated by Django 5.0.2 on 2024-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidoreal',
            name='goles_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='partidoreal',
            name='goles_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='partidoreal',
            name='jornada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partidoreal',
            name='winner',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
