# Generated by Django 5.0.2 on 2024-03-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0002_alter_partidosentrenamiento_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidoreal',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='partidosinpredecir',
            name='fecha',
        ),
    ]
