# Generated by Django 5.0.2 on 2024-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0002_alter_partidosentrenamiento_goles_ultimos_5_partidos_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidosentrenamiento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
