# Generated by Django 5.0.2 on 2024-03-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0002_alter_partidoreal_goles_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidoreal',
            name='fecha',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
