# Generated by Django 5.0.2 on 2024-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0003_alter_partidosentrenamiento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_5_partidos_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_5_partidos_local_siendo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_5_partidos_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_5_partidos_visitante_siendo_visitante',
            field=models.IntegerField(default=-1),
        ),
    ]
