# Generated by Django 5.0.2 on 2024-04-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0003_remove_partidoreal_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_3_partidos_equipo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_3_partidos_equipo_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_3_partidos_local_siendo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_en_contra_ultimos_3_partidos_visitante_siendo_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_ultimos_3_partidos_equipo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_ultimos_3_partidos_equipo_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_ultimos_3_partidos_local_siendo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='goles_ultimos_3_partidos_visitante_siendo_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='puntos_ultimos_3_partidos_equipo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='puntos_ultimos_3_partidos_equipo_visitante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='puntos_ultimos_3_partidos_local_siendo_local',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='puntos_ultimos_3_partidos_visitante_siendo_visitante',
            field=models.IntegerField(default=-1),
        ),
    ]
