# Generated by Django 5.0.2 on 2024-03-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0005_rename_goles_en_contra_ultimos_5_partidos_local_partidosentrenamiento_goles_en_contra_ultimos_5_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidosentrenamiento',
            old_name='puntos_ultimos_5_partidos_visitante',
            new_name='puntos_ultimos_5_partidos_equipo_visitante',
        ),
    ]
