# Generated by Django 5.0.2 on 2024-04-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0006_partidos_predichos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partidos_Predichos',
            new_name='PartidosPredichos',
        ),
    ]
