# Generated by Django 5.0.2 on 2024-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0006_rename_puntos_ultimos_5_partidos_visitante_partidosentrenamiento_puntos_ultimos_5_partidos_equipo_vi'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidosentrenamiento',
            name='falta',
            field=models.BooleanField(default=False),
        ),
    ]
