# Generated by Django 5.0.2 on 2024-04-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0007_rename_partidos_predichos_partidospredichos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidoreal',
            name='jornada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partidosinpredecir',
            name='jornada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partidospredichos',
            name='jornada',
            field=models.IntegerField(),
        ),
    ]
