# Generated by Django 5.0.2 on 2024-04-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0008_alter_partidoreal_jornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abierta', models.BooleanField(default=True)),
                ('primer_partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primer_partido', to='Predicciones.partidospredichos')),
                ('segundo_partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segundo_partido', to='Predicciones.partidospredichos')),
                ('tercer_partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tercer_partido', to='Predicciones.partidospredichos')),
            ],
        ),
    ]
