# Generated by Django 5.0.2 on 2024-04-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0010_quiniela_delete_porra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Porra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primer_partido', models.CharField(max_length=1)),
                ('segundo_partido', models.CharField(max_length=1)),
                ('tercer_partido', models.CharField(max_length=1)),
                ('cuarto_partido', models.CharField(max_length=1)),
                ('quinto_partido', models.CharField(max_length=1)),
                ('sexto_partido', models.CharField(max_length=1)),
                ('septimo_partido', models.CharField(max_length=1)),
                ('octavo_partido', models.CharField(max_length=1)),
                ('noveno_partido', models.CharField(max_length=1)),
                ('decimo_partido', models.CharField(max_length=1)),
                ('sin_puntuar', models.BooleanField(default=True)),
                ('puntos', models.IntegerField(default=0)),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Predicciones.quiniela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
