# Generated by Django 5.0.2 on 2024-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicciones', '0015_partidosentrenamiento_escudo_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoreal',
            name='escudo_local',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='partidoreal',
            name='escudo_visitante',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='partidoreal',
            name='logo_liga',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
